CREATE TABLE `T_USER` (
    `USR_ID` bigint NOT NULL AUTO_INCREMENT,
    `USR_ACCOUNT_NON_EXPIRED` bit(1) DEFAULT b'0',
    `USR_ACCOUNT_NOT_LOCKED` bit(1) DEFAULT b'0',
    `USR_CREDENTIALS_NON_EXPIRED` bit(1) DEFAULT b'0',
    `USR_ENABLED` bit(1) DEFAULT b'0',
    `USR_FIRST_NAME` varchar(30) DEFAULT NULL,
    `USR_LAST_NAME` varchar(30) DEFAULT NULL,
    `USR_PASSWORD` varchar(255) NOT NULL,
    `USR_USERNAME` varchar(30) NOT NULL,
    PRIMARY KEY (`USR_ID`),
    UNIQUE KEY `UK_h73iqyf4stp2gw3fskv90g3ba` (`USR_USERNAME`),
    KEY `USERNAME_INDEX` (`USR_USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `T_ROLE` (
    `ROL_ID` bigint NOT NULL AUTO_INCREMENT,
    `ROL_NAME` varchar(30) NOT NULL,
    PRIMARY KEY (`ROL_ID`),
    UNIQUE KEY `UK_4pwl3c4kt2uij6iwpwi5m705m` (`ROL_NAME`),
    KEY `ROLENAME_INDEX` (`ROL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `T_AUTHORITY` (
    `AUT_ID` bigint NOT NULL AUTO_INCREMENT,
    `AUT_NAME` varchar(30) NOT NULL,
    PRIMARY KEY (`AUT_ID`),
    UNIQUE KEY `UK_d7whq7bohope081q7l3drlv0w` (`AUT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `JT_USER_ROLE` (
    `USR_ID` bigint NOT NULL,
    `ROL_ID` bigint NOT NULL,
    UNIQUE KEY `UKsefuiilhgb8n04tgyo01nixm4` (`USR_ID`,`ROL_ID`),
    KEY `FKqjup32mrfkhd60r9crs3pfsye` (`ROL_ID`),
    CONSTRAINT `FK6r66h2t2ih4xe4jh8tsbx1ruy` FOREIGN KEY (`USR_ID`) REFERENCES `T_USER` (`USR_ID`),
    CONSTRAINT `FKqjup32mrfkhd60r9crs3pfsye` FOREIGN KEY (`ROL_ID`) REFERENCES `T_ROLE` (`ROL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `JT_ROLE_AUTHORITY` (
    `ROL_ID` bigint NOT NULL,
    `AUT_ID` bigint NOT NULL,
    UNIQUE KEY `UKcu8lk98s9h7bxtggjbxsh2v5` (`ROL_ID`,`AUT_ID`),
    KEY `FKp8u7qfnf1q0oh6wt1owyqgi9` (`AUT_ID`),
    CONSTRAINT `FK9hwjj9a74arepiv7aln0ujwbj` FOREIGN KEY (`ROL_ID`) REFERENCES `T_ROLE` (`ROL_ID`),
    CONSTRAINT `FKp8u7qfnf1q0oh6wt1owyqgi9` FOREIGN KEY (`AUT_ID`) REFERENCES `T_AUTHORITY` (`AUT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
